spring:
  mail:
    host: "${SMTP_HOST}"
    port: "${SMTP_PORT}"
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"